"""Generate committed Python and TypeScript contracts from the frozen baseline."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import OrderedDict
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import black
import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
CONTRACT_ROOT = PROJECT_ROOT / "docs" / "agent-platform"
BACKEND_GENERATED = PROJECT_ROOT / "backend" / "packages" / "contracts" / "generated"
FRONTEND_GENERATED = PROJECT_ROOT / "frontend" / "src" / "api" / "generated"
HTTP_METHODS = ("get", "post", "put", "patch", "delete")
GENERATED_HEADER = "Generated by scripts/generate_contracts.py. DO NOT EDIT."


class GenerationError(Exception):
    """Raised when a frozen contract cannot be converted deterministically."""


def load_yaml(path: Path) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise GenerationError(f"expected mapping in {path}")
    return value


def load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise GenerationError(f"expected mapping in {path}")
    return value


def pascal_case(value: str) -> str:
    words = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", value)
    words = re.sub(r"[^A-Za-z0-9]+", " ", words)
    return "".join(word[:1].upper() + word[1:] for word in words.split())


def snake_case(value: str) -> str:
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    value = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").lower()
    if value and value[0].isdigit():
        return f"value_{value}"
    return value


def camel_case(value: str) -> str:
    name = pascal_case(value)
    return name[:1].lower() + name[1:]


def quote_literal(value: Any, *, language: str) -> str:
    if value is None:
        return "None" if language == "python" else "null"
    if value is True:
        return "True" if language == "python" else "true"
    if value is False:
        return "False" if language == "python" else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    return repr(value)


def unique(values: Iterable[str]) -> list[str]:
    return list(dict.fromkeys(values))


def resolve_pointer(document: Mapping[str, Any], ref: str) -> Any:
    if not ref.startswith("#/"):
        raise GenerationError(f"not a local JSON pointer: {ref}")
    current: Any = document
    for raw_part in ref[2:].split("/"):
        part = raw_part.replace("~1", "/").replace("~0", "~")
        if not isinstance(current, Mapping) or part not in current:
            raise GenerationError(f"unresolved JSON pointer: {ref}")
        current = current[part]
    return current


def merge_object_schema(
    schema: Mapping[str, Any], document: Mapping[str, Any]
) -> dict[str, Any]:
    """Flatten local allOf object inheritance while preserving field overrides."""

    merged: dict[str, Any] = {
        "type": "object",
        "properties": OrderedDict(),
        "required": [],
    }
    additional_properties: Any = schema.get("additionalProperties")
    parts = schema.get("allOf")
    if isinstance(parts, list):
        for part in parts:
            if not isinstance(part, Mapping):
                continue
            if "$ref" in part and str(part["$ref"]).startswith("#/"):
                resolved = resolve_pointer(document, str(part["$ref"]))
                if not isinstance(resolved, Mapping):
                    raise GenerationError(f"allOf reference is not a schema: {part}")
                flattened = merge_object_schema(resolved, document)
            else:
                flattened = merge_object_schema(part, document)
            merged["properties"].update(flattened.get("properties", {}))
            merged["required"] = unique(
                [*merged["required"], *flattened.get("required", [])]
            )
            if "additionalProperties" in flattened:
                additional_properties = flattened["additionalProperties"]

    properties = schema.get("properties")
    if isinstance(properties, Mapping):
        merged["properties"].update(properties)
    required = schema.get("required")
    if isinstance(required, list):
        merged["required"] = unique([*merged["required"], *map(str, required)])
    if additional_properties is not None:
        merged["additionalProperties"] = additional_properties
    return merged


@dataclass(frozen=True)
class SchemaSource:
    document: Mapping[str, Any]
    local_names: Mapping[str, str]
    external_names: Mapping[str, str]


class SchemaRenderer:
    """Render the supported OpenAPI/JSON Schema subset into two typed languages."""

    def __init__(self, source: SchemaSource) -> None:
        self.source = source
        self.definitions: OrderedDict[str, Mapping[str, Any]] = OrderedDict()
        self.python_classes: list[str] = []

    def register(self, name: str, schema: Mapping[str, Any]) -> str:
        existing = self.definitions.get(name)
        if existing is not None and existing != schema:
            raise GenerationError(f"generated type name collision: {name}")
        self.definitions.setdefault(name, schema)
        return name

    def type_for_ref(self, ref: str) -> str:
        if ref in self.source.local_names:
            return self.source.local_names[ref]
        if ref in self.source.external_names:
            return self.source.external_names[ref]
        if ref.startswith("#/"):
            resolved = resolve_pointer(self.source.document, ref)
            if not isinstance(resolved, Mapping):
                raise GenerationError(f"reference does not target a schema: {ref}")
            name = pascal_case(ref.rsplit("/", maxsplit=1)[-1])
            return self.register(name, resolved)
        if ref == "https://json-schema.org/draft/2020-12/schema":
            return "JsonValue"
        raise GenerationError(f"unsupported external schema reference: {ref}")

    def python_type(self, schema: Mapping[str, Any], hint: str) -> str:
        ref = schema.get("$ref")
        if isinstance(ref, str):
            return self.type_for_ref(ref)
        if "const" in schema:
            return f"Literal[{quote_literal(schema['const'], language='python')}]"
        enum = schema.get("enum")
        if isinstance(enum, list):
            non_null = [value for value in enum if value is not None]
            rendered = (
                "Literal["
                + ", ".join(
                    quote_literal(value, language="python") for value in non_null
                )
                + "]"
                if non_null
                else "None"
            )
            return f"{rendered} | None" if len(non_null) != len(enum) else rendered
        for keyword in ("oneOf", "anyOf"):
            choices = schema.get(keyword)
            if isinstance(choices, list):
                rendered = unique(
                    self.python_type(choice, f"{hint}Choice{index + 1}")
                    for index, choice in enumerate(choices)
                    if isinstance(choice, Mapping)
                )
                return " | ".join(rendered) or "JsonValue"

        schema_type = schema.get("type")
        if isinstance(schema_type, list):
            rendered = unique(
                self.python_type({**schema, "type": item}, hint) for item in schema_type
            )
            return " | ".join(rendered)
        if schema_type == "string":
            return "datetime" if schema.get("format") == "date-time" else "str"
        if schema_type == "integer":
            return "int"
        if schema_type == "number":
            return "float"
        if schema_type == "boolean":
            return "bool"
        if schema_type == "null":
            return "None"
        if schema_type == "array":
            items = schema.get("items")
            item_schema = items if isinstance(items, Mapping) else {}
            return f"list[{self.python_type(item_schema, f'{hint}Item')}]"
        if schema_type == "object" or "properties" in schema or "allOf" in schema:
            properties = schema.get("properties")
            if isinstance(properties, Mapping) or "allOf" in schema:
                return self.register(hint, schema)
            additional = schema.get("additionalProperties")
            if isinstance(additional, Mapping):
                return f"dict[str, {self.python_type(additional, f'{hint}Value')}]"
            return "dict[str, JsonValue]"
        return "JsonValue"

    def typescript_type(self, schema: Mapping[str, Any], hint: str) -> str:
        ref = schema.get("$ref")
        if isinstance(ref, str):
            resolved = self.type_for_ref(ref)
            return "JSONValue" if resolved == "JsonValue" else resolved
        if "const" in schema:
            return quote_literal(schema["const"], language="typescript")
        enum = schema.get("enum")
        if isinstance(enum, list):
            return " | ".join(
                quote_literal(value, language="typescript") for value in enum
            )
        for keyword in ("oneOf", "anyOf"):
            choices = schema.get(keyword)
            if isinstance(choices, list):
                rendered = unique(
                    self.typescript_type(choice, f"{hint}Choice{index + 1}")
                    for index, choice in enumerate(choices)
                    if isinstance(choice, Mapping)
                )
                return " | ".join(rendered) or "JSONValue"

        schema_type = schema.get("type")
        if isinstance(schema_type, list):
            return " | ".join(
                unique(
                    self.typescript_type({**schema, "type": item}, hint)
                    for item in schema_type
                )
            )
        if schema_type == "string":
            return "string"
        if schema_type in {"integer", "number"}:
            return "number"
        if schema_type == "boolean":
            return "boolean"
        if schema_type == "null":
            return "null"
        if schema_type == "array":
            items = schema.get("items")
            item_schema = items if isinstance(items, Mapping) else {}
            item_type = self.typescript_type(item_schema, f"{hint}Item")
            return f"ReadonlyArray<{item_type}>"
        if schema_type == "object" or "properties" in schema or "allOf" in schema:
            properties = schema.get("properties")
            if isinstance(properties, Mapping) or "allOf" in schema:
                return self.register(hint, schema)
            additional = schema.get("additionalProperties")
            if isinstance(additional, Mapping):
                value_type = self.typescript_type(additional, f"{hint}Value")
                return f"Readonly<Record<string, {value_type}>>"
            return "Readonly<Record<string, JSONValue>>"
        return "JSONValue"

    def _python_field(
        self,
        owner: str,
        wire_name: str,
        schema: Mapping[str, Any],
        required: bool,
    ) -> str:
        field_name = snake_case(wire_name)
        annotation = self.python_type(schema, f"{owner}{pascal_case(wire_name)}")
        if not required and "None" not in annotation.split(" | "):
            annotation = f"{annotation} | None"

        default: str
        if required:
            default = "..."
        elif "default" in schema:
            default = quote_literal(schema["default"], language="python")
        else:
            default = "None"

        options: list[str] = []
        if field_name != wire_name:
            options.append(f"alias={quote_literal(wire_name, language='python')}")
        constraint_map = {
            "minLength": "min_length",
            "maxLength": "max_length",
            "minItems": "min_length",
            "maxItems": "max_length",
            "minProperties": "min_length",
            "maxProperties": "max_length",
            "minimum": "ge",
            "maximum": "le",
            "exclusiveMinimum": "gt",
            "exclusiveMaximum": "lt",
            "pattern": "pattern",
        }
        for schema_key, field_key in constraint_map.items():
            if schema_key in schema:
                options.append(
                    f"{field_key}={quote_literal(schema[schema_key], language='python')}"
                )

        if not options and required:
            return f"    {field_name}: {annotation}"
        if not options:
            return f"    {field_name}: {annotation} = {default}"
        return (
            f"    {field_name}: {annotation} = Field({default}, {', '.join(options)})"
        )

    def render_python_definition(self, name: str, schema: Mapping[str, Any]) -> str:
        if "$ref" in schema and len(schema) == 1:
            return f"type {name} = {self.python_type(schema, name)}"
        if (
            "const" in schema
            or "enum" in schema
            or "oneOf" in schema
            or "anyOf" in schema
        ):
            return f"type {name} = {self.python_type(schema, name)}"
        schema_type = schema.get("type")
        if schema_type not in {"object", None}:
            return f"type {name} = {self.python_type(schema, name)}"

        flattened = merge_object_schema(schema, self.source.document)
        properties = flattened.get("properties", {})
        if not isinstance(properties, Mapping):
            return f"type {name} = {self.python_type(schema, name)}"
        required = set(map(str, flattened.get("required", [])))
        extra = "forbid" if flattened.get("additionalProperties") is False else "allow"
        lines = [
            f"class {name}(BaseModel):",
            f'    model_config = ConfigDict(extra="{extra}", populate_by_name=True, regex_engine="python-re")',
        ]
        for wire_name, field_schema in properties.items():
            if not isinstance(field_schema, Mapping):
                raise GenerationError(f"invalid property schema: {name}.{wire_name}")
            lines.append(
                self._python_field(
                    name, str(wire_name), field_schema, str(wire_name) in required
                )
            )
        if not properties:
            lines.append("    pass")
        self.python_classes.append(name)
        return "\n".join(lines)

    def render_typescript_definition(self, name: str, schema: Mapping[str, Any]) -> str:
        if "$ref" in schema and len(schema) == 1:
            return f"export type {name} = {self.typescript_type(schema, name)};"
        if (
            "const" in schema
            or "enum" in schema
            or "oneOf" in schema
            or "anyOf" in schema
        ):
            return f"export type {name} = {self.typescript_type(schema, name)};"
        schema_type = schema.get("type")
        if schema_type not in {"object", None}:
            return f"export type {name} = {self.typescript_type(schema, name)};"

        flattened = merge_object_schema(schema, self.source.document)
        properties = flattened.get("properties", {})
        if not isinstance(properties, Mapping):
            return f"export type {name} = {self.typescript_type(schema, name)};"
        required = set(map(str, flattened.get("required", [])))
        lines = [f"export interface {name} {{"]
        for wire_name, field_schema in properties.items():
            if not isinstance(field_schema, Mapping):
                raise GenerationError(f"invalid property schema: {name}.{wire_name}")
            optional = "" if str(wire_name) in required else "?"
            field_type = self.typescript_type(
                field_schema, f"{name}{pascal_case(str(wire_name))}"
            )
            lines.append(f"  readonly {wire_name}{optional}: {field_type};")
        lines.append("}")
        return "\n".join(lines)

    def render_python_module(self, module_doc: str) -> str:
        rendered: list[str] = []
        index = 0
        while index < len(self.definitions):
            name = list(self.definitions)[index]
            rendered.append(self.render_python_definition(name, self.definitions[name]))
            index += 1
        rebuild = ""
        if self.python_classes:
            rebuild = (
                "\n\nfor _model in (\n"
                + "".join(f"    {name},\n" for name in self.python_classes)
                + "):\n    _model.model_rebuild()"
            )
        body = (
            "\n".join(f"{definition}{chr(10)}" for definition in rendered).rstrip()
            + rebuild
        )
        standard_imports: list[str] = []
        if re.search(r"\bdatetime\b", body):
            standard_imports.append("from datetime import datetime")
        if "Literal[" in body:
            standard_imports.append("from typing import Literal")
        pydantic_imports = ["BaseModel", "ConfigDict", "Field"]
        if re.search(r"\bJsonValue\b", body):
            pydantic_imports.append("JsonValue")
        source = f'''# {GENERATED_HEADER}
"""{module_doc}"""

from __future__ import annotations

{chr(10).join(standard_imports)}

from pydantic import {", ".join(pydantic_imports)}


{body}
'''
        return black.format_str(
            source,
            mode=black.Mode(
                line_length=88,
                target_versions={black.TargetVersion.PY312},
            ),
        )

    def render_typescript_module(self, module_doc: str) -> str:
        rendered: list[str] = []
        index = 0
        while index < len(self.definitions):
            name = list(self.definitions)[index]
            rendered.append(
                self.render_typescript_definition(name, self.definitions[name])
            )
            index += 1
        body = "\n\n".join(rendered)
        imports = (
            "import type { JSONValue } from './transport';\n\n"
            if re.search(r"\bJSONValue\b", body)
            else ""
        )
        return f"// {GENERATED_HEADER}\n" f"// {module_doc}\n\n" + imports + body + "\n"


@dataclass(frozen=True)
class ApiParameter:
    wire_name: str
    location: str
    required: bool
    schema: Mapping[str, Any]


@dataclass(frozen=True)
class ApiOperation:
    operation_id: str
    method: str
    path: str
    parameters: tuple[ApiParameter, ...]
    body_schema: Mapping[str, Any] | None
    body_required: bool
    response_schema: Mapping[str, Any] | None
    streaming: bool


def resolve_component(document: Mapping[str, Any], value: Any) -> Any:
    while isinstance(value, Mapping) and isinstance(value.get("$ref"), str):
        ref = str(value["$ref"])
        if not ref.startswith("#/"):
            return value
        value = resolve_pointer(document, ref)
    return value


def media_schema(
    document: Mapping[str, Any], value: Any, media_type: str
) -> Mapping[str, Any] | None:
    resolved = resolve_component(document, value)
    if not isinstance(resolved, Mapping):
        return None
    content = resolved.get("content")
    if not isinstance(content, Mapping):
        return None
    media = content.get(media_type)
    if not isinstance(media, Mapping):
        return None
    schema = media.get("schema")
    return schema if isinstance(schema, Mapping) else None


def parse_operations(document: Mapping[str, Any]) -> list[ApiOperation]:
    operations: list[ApiOperation] = []
    paths = document.get("paths")
    if not isinstance(paths, Mapping):
        raise GenerationError("OpenAPI paths must be a mapping")
    for path, path_item in paths.items():
        if not isinstance(path_item, Mapping):
            continue
        path_parameters = path_item.get("parameters", [])
        for method in HTTP_METHODS:
            operation = path_item.get(method)
            if not isinstance(operation, Mapping):
                continue
            operation_id = operation.get("operationId")
            if not isinstance(operation_id, str):
                raise GenerationError(f"missing operationId: {method} {path}")

            parameters: OrderedDict[tuple[str, str], ApiParameter] = OrderedDict()
            for raw_parameter in [*path_parameters, *operation.get("parameters", [])]:
                parameter = resolve_component(document, raw_parameter)
                if not isinstance(parameter, Mapping):
                    raise GenerationError(f"invalid parameter for {operation_id}")
                name = parameter.get("name")
                location = parameter.get("in")
                schema = parameter.get("schema", {})
                if not isinstance(name, str) or not isinstance(location, str):
                    raise GenerationError(
                        f"invalid parameter identity for {operation_id}"
                    )
                if not isinstance(schema, Mapping):
                    raise GenerationError(
                        f"invalid parameter schema for {operation_id}"
                    )
                parameters[(location, name)] = ApiParameter(
                    wire_name=name,
                    location=location,
                    required=location == "path" or bool(parameter.get("required")),
                    schema=schema,
                )

            request_body = resolve_component(document, operation.get("requestBody"))
            body_schema = media_schema(document, request_body, "application/json")
            body_required = bool(
                isinstance(request_body, Mapping) and request_body.get("required")
            )

            responses = operation.get("responses")
            if not isinstance(responses, Mapping):
                raise GenerationError(f"missing responses for {operation_id}")
            success_items = [
                (str(status), response)
                for status, response in responses.items()
                if str(status).startswith("2")
            ]
            if not success_items:
                raise GenerationError(f"missing success response for {operation_id}")
            _, success_response = min(success_items)
            response_schema = media_schema(
                document, success_response, "application/json"
            )
            streaming = (
                media_schema(document, success_response, "text/event-stream")
                is not None
            )
            operations.append(
                ApiOperation(
                    operation_id=operation_id,
                    method=method.upper(),
                    path=str(path),
                    parameters=tuple(parameters.values()),
                    body_schema=body_schema,
                    body_required=body_required,
                    response_schema=response_schema,
                    streaming=streaming,
                )
            )
    return operations


def operation_types(
    renderer: SchemaRenderer, operations: Iterable[ApiOperation]
) -> None:
    for operation in operations:
        for parameter in operation.parameters:
            renderer.register(
                f"{pascal_case(operation.operation_id)}{pascal_case(parameter.wire_name)}",
                parameter.schema,
            )
        if operation.body_schema is not None:
            renderer.python_type(
                operation.body_schema, f"{pascal_case(operation.operation_id)}Body"
            )
        if operation.response_schema is not None:
            renderer.python_type(
                operation.response_schema,
                f"{pascal_case(operation.operation_id)}Response",
            )


def render_python_transport() -> str:
    source = f'''# {GENERATED_HEADER}
"""Shared async HTTP transport for generated API clients."""

from __future__ import annotations

from collections.abc import AsyncGenerator, Mapping
from contextlib import AbstractAsyncContextManager, asynccontextmanager
from datetime import datetime
from urllib.parse import quote_plus

import httpx
from pydantic import BaseModel, JsonValue, TypeAdapter


type QueryScalar = str | int | float | bool | datetime
type QueryValue = QueryScalar | list[QueryScalar]

JSON_VALUE_ADAPTER: TypeAdapter[JsonValue] = TypeAdapter(JsonValue)


class ApiError(Exception):
    def __init__(self, status_code: int, payload: JsonValue | None) -> None:
        self.status_code = status_code
        self.payload = payload
        self.code = self._extract_code(payload)
        super().__init__(f"API request failed with HTTP {{status_code}}")

    @staticmethod
    def _extract_code(payload: JsonValue | None) -> str | None:
        if not isinstance(payload, dict):
            return None
        error = payload.get("error")
        if not isinstance(error, dict):
            return None
        code = error.get("code")
        return code if isinstance(code, str) else None


class AsyncApiTransport:
    def __init__(self, client: httpx.AsyncClient) -> None:
        self._client = client

    async def request(
        self,
        method: str,
        path: str,
        *,
        query: Mapping[str, QueryValue] | None = None,
        headers: Mapping[str, str] | None = None,
        body: BaseModel | JsonValue | None = None,
    ) -> JsonValue | None:
        response = await self._client.request(
            method,
            path,
            params=self._query_params(query),
            headers=headers,
            json=self._json_body(body),
        )
        if response.is_error:
            raise ApiError(response.status_code, self._response_payload(response))
        if response.status_code == 204 or not response.content:
            return None
        return JSON_VALUE_ADAPTER.validate_python(response.json())

    def open_stream(
        self,
        method: str,
        path: str,
        *,
        query: Mapping[str, QueryValue] | None = None,
        headers: Mapping[str, str] | None = None,
    ) -> AbstractAsyncContextManager[httpx.Response]:
        return self._stream(method, path, query=query, headers=headers)

    @asynccontextmanager
    async def _stream(
        self,
        method: str,
        path: str,
        *,
        query: Mapping[str, QueryValue] | None,
        headers: Mapping[str, str] | None,
    ) -> AsyncGenerator[httpx.Response, None]:
        async with self._client.stream(
            method, path, params=self._query_params(query), headers=headers
        ) as response:
            if response.is_error:
                await response.aread()
                raise ApiError(response.status_code, self._response_payload(response))
            yield response

    @staticmethod
    def _json_body(body: BaseModel | JsonValue | None) -> JsonValue | None:
        if isinstance(body, BaseModel):
            return JSON_VALUE_ADAPTER.validate_python(
                body.model_dump(mode="json", by_alias=True, exclude_none=True)
            )
        return body

    @staticmethod
    def _query_params(
        query: Mapping[str, QueryValue] | None,
    ) -> httpx.QueryParams | None:
        if query is None:
            return None
        encoded: list[str] = []
        for key, value in query.items():
            values = value if isinstance(value, list) else [value]
            for item in values:
                rendered = item.isoformat() if isinstance(item, datetime) else str(item)
                encoded.append(
                    f"{{quote_plus(key)}}={{quote_plus(rendered)}}"
                )
        return httpx.QueryParams("&".join(encoded))

    @staticmethod
    def _response_payload(response: httpx.Response) -> JsonValue | None:
        if not response.content:
            return None
        try:
            return JSON_VALUE_ADAPTER.validate_python(response.json())
        except ValueError:
            return None
'''
    return black.format_str(
        source,
        mode=black.Mode(
            line_length=88,
            target_versions={black.TargetVersion.PY312},
        ),
    )


def python_operation_parameters(
    renderer: SchemaRenderer, operation: ApiOperation
) -> list[tuple[str, str, bool, ApiParameter | None]]:
    values: list[tuple[str, str, bool, ApiParameter | None]] = []
    for parameter in operation.parameters:
        type_name = (
            f"{pascal_case(operation.operation_id)}{pascal_case(parameter.wire_name)}"
        )
        annotation = f"models.{type_name}"
        values.append(
            (snake_case(parameter.wire_name), annotation, parameter.required, parameter)
        )
    if operation.body_schema is not None:
        annotation = qualify_python_type(
            renderer.python_type(
                operation.body_schema, f"{pascal_case(operation.operation_id)}Body"
            ),
            renderer,
        )
        values.append(("body", annotation, operation.body_required, None))
    return sorted(values, key=lambda item: not item[2])


def qualify_type(expression: str, names: Iterable[str], prefix: str) -> str:
    for name in sorted(set(names), key=len, reverse=True):
        expression = re.sub(
            rf"(?<![.\w]){re.escape(name)}\b", f"{prefix}{name}", expression
        )
    return expression


def renderer_type_names(renderer: SchemaRenderer) -> set[str]:
    return {
        *renderer.definitions.keys(),
        *renderer.source.local_names.values(),
        *renderer.source.external_names.values(),
    } - {"JsonValue"}


def qualify_python_type(expression: str, renderer: SchemaRenderer) -> str:
    return qualify_type(expression, renderer_type_names(renderer), "models.")


def qualify_typescript_type(expression: str, renderer: SchemaRenderer) -> str:
    return qualify_type(expression, renderer_type_names(renderer), "Models.")


def render_python_client(
    class_name: str,
    models_module: str,
    renderer: SchemaRenderer,
    operations: list[ApiOperation],
) -> str:
    has_streaming = any(operation.streaming for operation in operations)
    lines = [
        f"# {GENERATED_HEADER}",
        f'"""Generated {class_name} methods."""',
        "",
        "from __future__ import annotations",
        "",
        *(
            ["from contextlib import AbstractAsyncContextManager"]
            if has_streaming
            else []
        ),
        "from urllib.parse import quote",
        "",
        *(["import httpx"] if has_streaming else []),
        "from pydantic import TypeAdapter",
        "",
        f"from . import {models_module} as models",
        "from .transport import AsyncApiTransport, QueryValue",
        "",
        "",
        "OPERATION_IDS = frozenset(",
        "    {",
        *[f'        "{operation.operation_id}",' for operation in operations],
        "    }",
        ")",
        "",
        "",
        f"class {class_name}:",
        "    def __init__(self, transport: AsyncApiTransport) -> None:",
        "        self._transport = transport",
    ]
    for operation in operations:
        params = python_operation_parameters(renderer, operation)
        method_name = snake_case(operation.operation_id)
        response_type = (
            qualify_python_type(
                renderer.python_type(
                    operation.response_schema,
                    f"{pascal_case(operation.operation_id)}Response",
                ),
                renderer,
            )
            if operation.response_schema is not None
            else "None"
        )
        return_type = (
            "AbstractAsyncContextManager[httpx.Response]"
            if operation.streaming
            else response_type
        )
        lines.extend(
            [
                "",
                f"    {'def' if operation.streaming else 'async def'} {method_name}(",
                "        self,",
            ]
        )
        if params:
            lines.append("        *,")
            for name, annotation, required, _ in params:
                default = "" if required else " = None"
                if not required:
                    annotation = f"{annotation} | None"
                lines.append(f"        {name}: {annotation}{default},")
        lines.append(f"    ) -> {return_type}:")

        path_expression = repr(operation.path)
        for parameter in operation.parameters:
            if parameter.location == "path":
                name = snake_case(parameter.wire_name)
                path_expression += f'.replace("{{{parameter.wire_name}}}", quote(str({name}), safe=""))'
        lines.append(f"        path = {path_expression}")

        query_parameters = [p for p in operation.parameters if p.location == "query"]
        header_parameters = [p for p in operation.parameters if p.location == "header"]
        if query_parameters:
            lines.extend(["        query: dict[str, QueryValue] = {}"])
            for parameter in query_parameters:
                name = snake_case(parameter.wire_name)
                if parameter.required:
                    lines.append(f'        query["{parameter.wire_name}"] = {name}')
                else:
                    lines.extend(
                        [
                            f"        if {name} is not None:",
                            f'            query["{parameter.wire_name}"] = {name}',
                        ]
                    )
        if header_parameters:
            lines.append("        headers: dict[str, str] = {}")
            for parameter in header_parameters:
                name = snake_case(parameter.wire_name)
                if parameter.required:
                    lines.append(
                        f'        headers["{parameter.wire_name}"] = str({name})'
                    )
                else:
                    lines.extend(
                        [
                            f"        if {name} is not None:",
                            f'            headers["{parameter.wire_name}"] = str({name})',
                        ]
                    )
        query_arg = "query=query" if query_parameters else "query=None"
        headers_arg = "headers=headers" if header_parameters else "headers=None"
        if operation.streaming:
            lines.extend(
                [
                    "        return self._transport.open_stream(",
                    f'            "{operation.method}", path, {query_arg}, {headers_arg}',
                    "        )",
                ]
            )
            continue
        body_arg = "body=body" if operation.body_schema is not None else "body=None"
        lines.extend(
            [
                "        payload = await self._transport.request(",
                f'            "{operation.method}",',
                "            path,",
                f"            {query_arg},",
                f"            {headers_arg},",
                f"            {body_arg},",
                "        )",
            ]
        )
        if response_type == "None":
            lines.append("        return None")
        else:
            lines.append(
                f"        return TypeAdapter({response_type}).validate_python(payload)"
            )

    return black.format_str(
        "\n".join(lines) + "\n",
        mode=black.Mode(
            line_length=88,
            target_versions={black.TargetVersion.PY312},
        ),
    )


def render_typescript_transport() -> str:
    return f"""// {GENERATED_HEADER}
// Shared fetch transport for generated API clients.

export type JSONValue =
  | string
  | number
  | boolean
  | null
  | ReadonlyArray<JSONValue>
  | {{ readonly [key: string]: JSONValue }};

export type QueryValue = string | number | boolean | ReadonlyArray<string | number | boolean>;

export interface ApiRequest {{
  readonly method: string;
  readonly path: string;
  readonly query?: Readonly<Record<string, QueryValue | undefined>>;
  readonly headers?: Readonly<Record<string, string | undefined>>;
  readonly body?: unknown;
  readonly signal?: AbortSignal | undefined;
}}

export class ApiError extends Error {{
  readonly statusCode: number;
  readonly code: string | undefined;
  readonly payload: unknown;

  constructor(statusCode: number, payload: unknown) {{
    super(`API request failed with HTTP ${{statusCode}}`);
    this.name = 'ApiError';
    this.statusCode = statusCode;
    this.payload = payload;
    this.code = extractErrorCode(payload);
  }}
}}

export interface ApiTransport {{
  request<T>(request: ApiRequest): Promise<T>;
  openStream(request: ApiRequest): Promise<Response>;
}}

export class FetchApiTransport implements ApiTransport {{
  private readonly baseUrl: string;
  private readonly requestTimeoutMs: number;
  private readonly fetcher: typeof fetch;

  constructor(options: {{
    readonly baseUrl?: string;
    readonly requestTimeoutMs?: number;
    readonly fetcher?: typeof fetch;
  }} = {{}}) {{
    this.baseUrl = options.baseUrl ?? '';
    this.requestTimeoutMs = options.requestTimeoutMs ?? 10_000;
    this.fetcher = options.fetcher ?? fetch;
  }}

  async request<T>(request: ApiRequest): Promise<T> {{
    const controller = new AbortController();
    const abortFromCaller = (): void => controller.abort(request.signal?.reason);
    request.signal?.addEventListener('abort', abortFromCaller, {{ once: true }});
    const timeout = setTimeout(
      () => controller.abort('API request timeout'),
      this.requestTimeoutMs,
    );
    try {{
      const init: RequestInit = {{
        method: request.method,
        headers: this.buildHeaders(request),
        credentials: 'same-origin',
        signal: controller.signal,
      }};
      if (request.body !== undefined) init.body = JSON.stringify(request.body);
      const response = await this.fetcher(this.buildUrl(request), init);
      return await this.parseResponse<T>(response);
    }} finally {{
      clearTimeout(timeout);
      request.signal?.removeEventListener('abort', abortFromCaller);
    }}
  }}

  async openStream(request: ApiRequest): Promise<Response> {{
    const init: RequestInit = {{
      method: request.method,
      headers: this.buildHeaders(request),
      credentials: 'same-origin',
    }};
    if (request.signal !== undefined) init.signal = request.signal;
    const response = await this.fetcher(this.buildUrl(request), init);
    if (!response.ok) {{
      throw new ApiError(response.status, await readPayload(response));
    }}
    return response;
  }}

  private buildUrl(request: ApiRequest): string {{
    const url = new URL(`${{this.baseUrl}}${{request.path}}`, window.location.origin);
    for (const [key, value] of Object.entries(request.query ?? {{}})) {{
      if (value === undefined) continue;
      const values = Array.isArray(value) ? value : [value];
      for (const item of values) url.searchParams.append(key, String(item));
    }}
    return url.toString();
  }}

  private buildHeaders(request: ApiRequest): Headers {{
    const headers = new Headers({{ Accept: 'application/json' }});
    for (const [key, value] of Object.entries(request.headers ?? {{}})) {{
      if (value !== undefined) headers.set(key, value);
    }}
    if (request.body !== undefined) headers.set('Content-Type', 'application/json');
    return headers;
  }}

  private async parseResponse<T>(response: Response): Promise<T> {{
    const payload = await readPayload(response);
    if (!response.ok) throw new ApiError(response.status, payload);
    return payload as T;
  }}
}}

function extractErrorCode(payload: unknown): string | undefined {{
  if (typeof payload !== 'object' || payload === null || !('error' in payload)) return undefined;
  const error = payload.error;
  if (typeof error !== 'object' || error === null || !('code' in error)) return undefined;
  return typeof error.code === 'string' ? error.code : undefined;
}}

async function readPayload(response: Response): Promise<unknown> {{
  if (response.status === 204) return undefined;
  const text = await response.text();
  if (!text) return undefined;
  try {{
    return JSON.parse(text) as unknown;
  }} catch {{
    return text;
  }}
}}
"""


def typescript_operation_input(
    renderer: SchemaRenderer, operation: ApiOperation
) -> list[tuple[str, str, bool, ApiParameter | None]]:
    values: list[tuple[str, str, bool, ApiParameter | None]] = []
    for parameter in operation.parameters:
        annotation = (
            f"Models.{pascal_case(operation.operation_id)}"
            f"{pascal_case(parameter.wire_name)}"
        )
        values.append(
            (camel_case(parameter.wire_name), annotation, parameter.required, parameter)
        )
    if operation.body_schema is not None:
        values.append(
            (
                "body",
                qualify_typescript_type(
                    renderer.typescript_type(
                        operation.body_schema,
                        f"{pascal_case(operation.operation_id)}Body",
                    ),
                    renderer,
                ),
                operation.body_required,
                None,
            )
        )
    values.append(("signal", "AbortSignal", False, None))
    return values


def render_typescript_client(
    class_name: str,
    models_module: str,
    renderer: SchemaRenderer,
    operations: list[ApiOperation],
) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        f"// Generated {class_name} methods.",
        "",
        f"import type * as Models from './{models_module}';",
        "import type { ApiTransport } from './transport';",
        "",
        "export const operationIds = [",
        *[f"  '{operation.operation_id}'," for operation in operations],
        "] as const;",
        "",
        f"export class {class_name} {{",
        "  private readonly transport: ApiTransport;",
        "",
        "  constructor(transport: ApiTransport) {",
        "    this.transport = transport;",
        "  }",
    ]
    for operation in operations:
        input_values = typescript_operation_input(renderer, operation)
        required_input = any(value[2] for value in input_values)
        lines.extend(["", f"  async {operation.operation_id}(", "    input: {"])
        for name, annotation, required, _ in input_values:
            optional = "" if required else "?"
            lines.append(f"      readonly {name}{optional}: {annotation};")
        lines.append(f"    }}{' = {}' if not required_input else ''},")
        response_type = (
            qualify_typescript_type(
                renderer.typescript_type(
                    operation.response_schema,
                    f"{pascal_case(operation.operation_id)}Response",
                ),
                renderer,
            )
            if operation.response_schema is not None
            else "undefined"
        )
        return_type = "Response" if operation.streaming else response_type
        lines.append(f"  ): Promise<{return_type}> {{")
        path_expression = f"'{operation.path}'"
        for parameter in operation.parameters:
            if parameter.location == "path":
                name = camel_case(parameter.wire_name)
                path_expression += f".replace('{{{parameter.wire_name}}}', encodeURIComponent(String(input.{name})))"
        lines.append(f"    const path = {path_expression};")

        query_parameters = [p for p in operation.parameters if p.location == "query"]
        header_parameters = [p for p in operation.parameters if p.location == "header"]
        call = "openStream" if operation.streaming else f"request<{response_type}>"
        lines.extend(
            [
                f"    return await this.transport.{call}({{",
                f"      method: '{operation.method}',",
                "      path,",
            ]
        )
        if query_parameters:
            lines.append("      query: {")
            for parameter in query_parameters:
                name = camel_case(parameter.wire_name)
                lines.append(f"        '{parameter.wire_name}': input.{name},")
            lines.append("      },")
        if header_parameters:
            lines.append("      headers: {")
            for parameter in header_parameters:
                name = camel_case(parameter.wire_name)
                value = (
                    f"String(input.{name})"
                    if parameter.required
                    else f"input.{name} === undefined ? undefined : String(input.{name})"
                )
                lines.append(f"        '{parameter.wire_name}': {value},")
            lines.append("      },")
        if operation.body_schema is not None:
            lines.append("      body: input.body,")
        lines.extend(["      signal: input.signal,", "    });", "  }"])
    lines.extend(["}", ""])
    return "\n".join(lines)


def schema_name_maps() -> (
    tuple[dict[str, str], dict[str, str], dict[str, str], dict[str, str]]
):
    resource = load_json(CONTRACT_ROOT / "schemas" / "resource-content-v1.schema.json")
    skill = load_json(CONTRACT_ROOT / "schemas" / "skill-manifest-v1.schema.json")
    run_event = load_json(CONTRACT_ROOT / "schemas" / "run-event-v1.schema.json")

    resource_names = {"#": "ResourceContent"}
    resource_names.update(
        {
            f"#/$defs/{name}": f"ResourceContent{pascal_case(name)}"
            for name in resource.get("$defs", {})
        }
    )
    skill_names = {"#": "SkillManifest"}
    skill_names.update(
        {
            f"#/$defs/{name}": f"SkillManifest{pascal_case(name)}"
            for name in skill.get("$defs", {})
        }
    )
    sandbox_names = {"#": "SandboxPolicy"}
    run_event_names = {"#": "RunEvent"}
    run_event_names.update(
        {f"#/$defs/{name}": pascal_case(name) for name in run_event.get("$defs", {})}
    )
    return resource_names, skill_names, sandbox_names, run_event_names


def render_supporting_models() -> tuple[str, str]:
    resource = load_json(CONTRACT_ROOT / "schemas" / "resource-content-v1.schema.json")
    skill = load_json(CONTRACT_ROOT / "schemas" / "skill-manifest-v1.schema.json")
    sandbox = load_json(CONTRACT_ROOT / "schemas" / "sandbox-policy-v1.schema.json")
    resource_names, skill_names, sandbox_names, _ = schema_name_maps()

    combined: dict[str, Any] = {"$defs": {}}
    local_names: dict[str, str] = {}
    for prefix, document, names in (
        ("resource", resource, resource_names),
        ("skill", skill, skill_names),
        ("sandbox", sandbox, sandbox_names),
    ):
        root_pointer = f"#/$defs/{prefix}_root"
        combined["$defs"][f"{prefix}_root"] = document
        local_names[root_pointer] = names["#"]
        for pointer, type_name in names.items():
            if pointer == "#":
                continue
            def_name = pointer.rsplit("/", maxsplit=1)[-1]
            combined_pointer = f"#/$defs/{prefix}_{def_name}"
            combined["$defs"][f"{prefix}_{def_name}"] = document["$defs"][def_name]
            local_names[combined_pointer] = type_name

    external_names: dict[str, str] = {
        "skill-manifest-v1.schema.json": "SkillManifest",
        "sandbox-policy-v1.schema.json": "SandboxPolicy",
        "https://json-schema.org/draft/2020-12/schema": "JsonValue",
    }
    for type_name in local_names.values():
        external_names[f"generated://{type_name}"] = type_name
    for pointer, type_name in resource_names.items():
        if pointer != "#":
            external_names[pointer] = type_name

    renderer = SchemaRenderer(
        SchemaSource(
            document=combined,
            local_names=local_names,
            external_names=external_names,
        )
    )
    ordered_supporting_types = sorted(
        local_names.items(), key=lambda item: item[1] == "ResourceContent"
    )
    for pointer, name in ordered_supporting_types:
        schema = resolve_pointer(combined, pointer)
        if not isinstance(schema, Mapping):
            raise GenerationError(f"invalid supporting schema: {pointer}")
        adjusted = replace_local_refs(
            schema, pointer.split("_")[0], resource_names, skill_names
        )
        renderer.register(name, adjusted)
    return (
        renderer.render_python_module("Generated resource content DTOs."),
        renderer.render_typescript_module("Generated resource content DTOs."),
    )


def replace_local_refs(
    value: Any,
    prefix_hint: str,
    resource_names: Mapping[str, str],
    skill_names: Mapping[str, str],
) -> Any:
    """Map local refs from combined supporting documents to generated names."""

    if isinstance(value, list):
        return [
            replace_local_refs(item, prefix_hint, resource_names, skill_names)
            for item in value
        ]
    if not isinstance(value, Mapping):
        return value
    result: dict[str, Any] = {}
    for key, item in value.items():
        if key == "$ref" and isinstance(item, str) and item.startswith("#/$defs/"):
            names = skill_names if "skill" in prefix_hint else resource_names
            result[key] = f"generated://{names[item]}"
        else:
            result[key] = replace_local_refs(
                item, prefix_hint, resource_names, skill_names
            )
    return result


def render_run_event_models() -> tuple[str, str]:
    document = load_json(CONTRACT_ROOT / "schemas" / "run-event-v1.schema.json")
    _, _, _, run_event_names = schema_name_maps()
    external_names = {f"generated://{name}": name for name in run_event_names.values()}
    source = SchemaSource(
        document=document,
        local_names=run_event_names,
        external_names=external_names,
    )
    python_renderer = SchemaRenderer(source)
    typescript_renderer = SchemaRenderer(source)
    support_defs = [
        name
        for name in document.get("$defs", {})
        if name.endswith("_payload")
        or name in {"artifact_ref", "plan_step", "usage", "id"}
    ]
    for name in support_defs:
        schema = document["$defs"][name]
        type_name = run_event_names[f"#/$defs/{name}"]
        python_renderer.register(type_name, schema)
        typescript_renderer.register(type_name, schema)

    python_base = python_renderer.render_python_module(
        "Generated RunEvent payload DTOs."
    ).rstrip()
    python_base = python_base.replace(
        "from typing import Literal",
        "from typing import Annotated, Literal",
    )
    python_base = re.sub(
        r"from pydantic import ([^\n]+)",
        lambda match: f"from pydantic import {match.group(1)}, TypeAdapter",
        python_base,
        count=1,
    )
    typescript_base = typescript_renderer.render_typescript_module(
        "Generated RunEvent payload DTOs."
    ).rstrip()
    variants = run_event_variants(document)
    envelope = resolve_pointer(document, "#/$defs/envelope")
    runtime_candidate = resolve_pointer(document, "#/$defs/runtime_event_candidate")
    if not isinstance(envelope, Mapping) or not isinstance(runtime_candidate, Mapping):
        raise GenerationError("RunEvent envelope schemas are invalid")
    candidate_parts = runtime_candidate.get("allOf")
    if not isinstance(candidate_parts, list) or not candidate_parts:
        raise GenerationError("RuntimeEventCandidate must use allOf")
    candidate_envelope = candidate_parts[0]
    if not isinstance(candidate_envelope, Mapping):
        raise GenerationError("RuntimeEventCandidate envelope is invalid")

    python_extra = render_python_event_unions(
        python_renderer, envelope, candidate_envelope, variants
    )
    typescript_extra = render_typescript_event_unions(
        typescript_renderer, envelope, candidate_envelope, variants
    )
    return (
        black.format_str(
            python_base + "\n\n" + python_extra,
            mode=black.Mode(
                line_length=88,
                target_versions={black.TargetVersion.PY312},
            ),
        ),
        typescript_base + "\n\n" + typescript_extra,
    )


def render_run_event_schema() -> str:
    """Expose the frozen schema to browser runtime validation deterministically."""

    document = load_json(CONTRACT_ROOT / "schemas" / "run-event-v1.schema.json")
    return json.dumps(document, ensure_ascii=False, indent=2) + "\n"


def run_event_variants(document: Mapping[str, Any]) -> list[tuple[str, str, str]]:
    root_all_of = document.get("allOf")
    if not isinstance(root_all_of, list) or len(root_all_of) < 2:
        raise GenerationError("RunEvent root must use envelope + oneOf")
    variant_group = root_all_of[1]
    if not isinstance(variant_group, Mapping):
        raise GenerationError("RunEvent variant group is invalid")
    choices = variant_group.get("oneOf")
    if not isinstance(choices, list):
        raise GenerationError("RunEvent variants must use oneOf")
    variants: list[tuple[str, str, str]] = []
    for choice in choices:
        if not isinstance(choice, Mapping) or not isinstance(choice.get("$ref"), str):
            raise GenerationError("RunEvent variant must be a reference")
        variant = resolve_pointer(document, str(choice["$ref"]))
        if not isinstance(variant, Mapping):
            raise GenerationError("RunEvent variant is invalid")
        properties = variant.get("properties")
        if not isinstance(properties, Mapping):
            raise GenerationError("RunEvent variant properties are invalid")
        event_type_schema = properties.get("event_type")
        payload_schema = properties.get("payload")
        if not isinstance(event_type_schema, Mapping) or not isinstance(
            payload_schema, Mapping
        ):
            raise GenerationError("RunEvent variant fields are invalid")
        event_type = event_type_schema.get("const")
        payload_ref = payload_schema.get("$ref")
        if not isinstance(event_type, str) or not isinstance(payload_ref, str):
            raise GenerationError("RunEvent variant discriminator is invalid")
        variants.append(
            (
                event_type,
                pascal_case(event_type) + "Event",
                pascal_case(payload_ref.rsplit("/", maxsplit=1)[-1]),
            )
        )
    return variants


def render_python_event_unions(
    renderer: SchemaRenderer,
    envelope: Mapping[str, Any],
    candidate_envelope: Mapping[str, Any],
    variants: list[tuple[str, str, str]],
) -> str:
    envelope_schema = {**envelope}
    envelope_properties = dict(envelope_schema.get("properties", {}))
    envelope_properties.pop("event_type", None)
    envelope_properties.pop("payload", None)
    envelope_schema["properties"] = envelope_properties
    envelope_schema["required"] = [
        item
        for item in envelope_schema.get("required", [])
        if item not in {"event_type", "payload"}
    ]
    candidate_schema = {**candidate_envelope}
    candidate_properties = dict(candidate_schema.get("properties", {}))
    candidate_properties.pop("event_type", None)
    candidate_properties.pop("payload", None)
    candidate_schema["properties"] = candidate_properties
    candidate_schema["required"] = [
        item
        for item in candidate_schema.get("required", [])
        if item not in {"event_type", "payload"}
    ]
    renderer.python_classes = []
    base = renderer.render_python_definition("RunEventEnvelope", envelope_schema)
    candidate_base = renderer.render_python_definition(
        "RuntimeEventCandidateEnvelope", candidate_schema
    )
    lines = [base, "", candidate_base]
    event_names: list[str] = []
    candidate_names: list[str] = []
    for event_type, event_name, payload_name in variants:
        candidate_name = event_name.removesuffix("Event") + "Candidate"
        event_names.append(event_name)
        candidate_names.append(candidate_name)
        lines.extend(
            [
                "",
                f"class {event_name}(RunEventEnvelope):",
                f'    event_type: Literal["{event_type}"]',
                f"    payload: {payload_name}",
                "",
                f"class {candidate_name}(RuntimeEventCandidateEnvelope):",
                f'    event_type: Literal["{event_type}"]',
                f"    payload: {payload_name}",
            ]
        )
    lines.extend(
        [
            "",
            "type RunEvent = Annotated[",
            "    " + " | ".join(event_names) + ",",
            '    Field(discriminator="event_type"),',
            "]",
            "type RuntimeEventCandidate = Annotated[",
            "    " + " | ".join(candidate_names) + ",",
            '    Field(discriminator="event_type"),',
            "]",
            "RUN_EVENT_ADAPTER: TypeAdapter[RunEvent] = TypeAdapter(RunEvent)",
            "RUNTIME_EVENT_CANDIDATE_ADAPTER: TypeAdapter[RuntimeEventCandidate] = TypeAdapter(RuntimeEventCandidate)",
        ]
    )
    return "\n".join(lines) + "\n"


def render_typescript_event_unions(
    renderer: SchemaRenderer,
    envelope: Mapping[str, Any],
    candidate_envelope: Mapping[str, Any],
    variants: list[tuple[str, str, str]],
) -> str:
    def base_interface(name: str, schema: Mapping[str, Any]) -> str:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        lines = [f"export interface {name} {{"]
        if isinstance(properties, Mapping):
            for field, field_schema in properties.items():
                if field in {"event_type", "payload"} or not isinstance(
                    field_schema, Mapping
                ):
                    continue
                optional = "" if field in required else "?"
                annotation = renderer.typescript_type(
                    field_schema, f"{name}{pascal_case(str(field))}"
                )
                lines.append(f"  readonly {field}{optional}: {annotation};")
        lines.append("}")
        return "\n".join(lines)

    lines = [
        base_interface("RunEventEnvelope", envelope),
        "",
        base_interface("RuntimeEventCandidateEnvelope", candidate_envelope),
    ]
    event_names: list[str] = []
    candidate_names: list[str] = []
    for event_type, event_name, payload_name in variants:
        candidate_name = event_name.removesuffix("Event") + "Candidate"
        event_names.append(event_name)
        candidate_names.append(candidate_name)
        lines.extend(
            [
                "",
                f"export interface {event_name} extends RunEventEnvelope {{",
                f"  readonly event_type: '{event_type}';",
                f"  readonly payload: {payload_name};",
                "}",
                "",
                f"export interface {candidate_name} extends RuntimeEventCandidateEnvelope {{",
                f"  readonly event_type: '{event_type}';",
                f"  readonly payload: {payload_name};",
                "}",
            ]
        )
    lines.extend(
        [
            "",
            "export type RunEvent =",
            *[f"  | {name}" for name in event_names],
            ";",
            "",
            "export type RuntimeEventCandidate =",
            *[f"  | {name}" for name in candidate_names],
            ";",
            "",
            "export const runEventTypes = [",
            *[f"  '{event_type}'," for event_type, _, _ in variants],
            "] as const;",
        ]
    )
    return "\n".join(lines) + "\n"


def openapi_renderer(document: Mapping[str, Any], *, resources: bool) -> SchemaRenderer:
    schemas = document.get("components", {}).get("schemas", {})
    if not isinstance(schemas, Mapping):
        raise GenerationError("OpenAPI components.schemas must be a mapping")
    local_names = {f"#/components/schemas/{name}": str(name) for name in schemas}
    external_names = {
        "./schemas/run-event-v1.schema.json": "RunEvent",
        "./schemas/run-event-v1.schema.json#/$defs/runtime_event_candidate": "RuntimeEventCandidate",
        "./schemas/resource-content-v1.schema.json": "ResourceContent",
    }
    resource_names, _, _, _ = schema_name_maps()
    for pointer, type_name in resource_names.items():
        if pointer == "#":
            continue
        external_names[f"./schemas/resource-content-v1.schema.json{pointer}"] = (
            type_name
        )
    renderer = SchemaRenderer(
        SchemaSource(
            document=document,
            local_names=local_names,
            external_names=external_names,
        )
    )
    for name, schema in schemas.items():
        if not isinstance(schema, Mapping):
            raise GenerationError(f"invalid OpenAPI schema: {name}")
        if not resources and name in {"RunEvent", "RuntimeEventCandidate"}:
            continue
        renderer.register(str(name), schema)
    return renderer


def render_openapi_outputs(
    filename: str,
    models_name: str,
    client_name: str,
    class_name: str,
    *,
    resources: bool,
) -> tuple[str, str, str, str]:
    document = load_yaml(CONTRACT_ROOT / filename)
    operations = parse_operations(document)
    python_renderer = openapi_renderer(document, resources=resources)
    typescript_renderer = openapi_renderer(document, resources=resources)
    operation_types(python_renderer, operations)
    operation_types(typescript_renderer, operations)
    python_models = python_renderer.render_python_module(
        f"DTOs generated from {filename}."
    )
    typescript_models = typescript_renderer.render_typescript_module(
        f"DTOs generated from {filename}."
    )
    if not resources:
        python_models = python_models.replace(
            "from pydantic import BaseModel, ConfigDict, Field, JsonValue\n",
            "from pydantic import BaseModel, ConfigDict, Field, JsonValue\n\n"
            "from .run_event import RunEvent, RuntimeEventCandidate\n",
        )
        typescript_models = typescript_models.replace(
            "import type { JSONValue } from './transport';\n",
            "import type { JSONValue } from './transport';\n"
            "import type { RunEvent, RuntimeEventCandidate } from './run-event';\n",
        )
    else:
        python_models = python_models.replace(
            "from pydantic import BaseModel, ConfigDict, Field, JsonValue\n",
            "from pydantic import BaseModel, ConfigDict, Field, JsonValue\n\n"
            "from .resource_content import (\n"
            "    ResourceContent,\n"
            "    ResourceContentMcp,\n"
            "    ResourceContentModelConfig,\n"
            "    ResourceContentModelProvider,\n"
            "    ResourceContentPrompt,\n"
            "    ResourceContentRuntimeTarget,\n"
            "    ResourceContentSandboxProfile,\n"
            "    ResourceContentSkill,\n"
            ")\n",
        )
        typescript_models = typescript_models.replace(
            "import type { JSONValue } from './transport';\n",
            "import type { JSONValue } from './transport';\n"
            "import type {\n"
            "  ResourceContent,\n"
            "  ResourceContentMcp,\n"
            "  ResourceContentModelConfig,\n"
            "  ResourceContentModelProvider,\n"
            "  ResourceContentPrompt,\n"
            "  ResourceContentRuntimeTarget,\n"
            "  ResourceContentSandboxProfile,\n"
            "  ResourceContentSkill,\n"
            "} from './resource-content';\n",
        )
    return (
        python_models,
        render_python_client(class_name, models_name, python_renderer, operations),
        typescript_models,
        render_typescript_client(
            class_name, models_name.replace("_", "-"), typescript_renderer, operations
        ),
    )


def render_outputs() -> dict[Path, str]:
    supporting_python, supporting_typescript = render_supporting_models()
    run_event_python, run_event_typescript = render_run_event_models()
    run_event_schema = render_run_event_schema()
    core_python, core_client_python, core_ts, core_client_ts = render_openapi_outputs(
        "agent-platform-openapi-v1.yaml",
        "core_models",
        "core_client",
        "CoreApiClient",
        resources=False,
    )
    resources_python, resources_client_python, resources_ts, resources_client_ts = (
        render_openapi_outputs(
            "agent-platform-openapi-resources-v1.yaml",
            "resources_models",
            "resources_client",
            "ResourcesApiClient",
            resources=True,
        )
    )
    backend_init = f'''# {GENERATED_HEADER}
"""Generated contract DTOs and API clients."""
'''
    frontend_index = f"""// {GENERATED_HEADER}
export {{ CoreApiClient, operationIds as coreOperationIds }} from './core-client';
export type * as CoreModels from './core-models';
export * from './resource-content';
export {{ ResourcesApiClient, operationIds as resourceOperationIds }} from './resources-client';
export type * as ResourcesModels from './resources-models';
export * from './run-event';
export * from './transport';
"""
    return {
        BACKEND_GENERATED / "__init__.py": backend_init,
        BACKEND_GENERATED / "transport.py": render_python_transport(),
        BACKEND_GENERATED / "resource_content.py": supporting_python,
        BACKEND_GENERATED / "run_event.py": run_event_python,
        BACKEND_GENERATED / "core_models.py": core_python,
        BACKEND_GENERATED / "core_client.py": core_client_python,
        BACKEND_GENERATED / "resources_models.py": resources_python,
        BACKEND_GENERATED / "resources_client.py": resources_client_python,
        FRONTEND_GENERATED / "transport.ts": render_typescript_transport(),
        FRONTEND_GENERATED / "resource-content.ts": supporting_typescript,
        FRONTEND_GENERATED / "run-event.ts": run_event_typescript,
        FRONTEND_GENERATED / "run-event.schema.json": run_event_schema,
        FRONTEND_GENERATED / "core-models.ts": core_ts,
        FRONTEND_GENERATED / "core-client.ts": core_client_ts,
        FRONTEND_GENERATED / "resources-models.ts": resources_ts,
        FRONTEND_GENERATED / "resources-client.ts": resources_client_ts,
        FRONTEND_GENERATED / "index.ts": frontend_index,
    }


def expected_generated_files(outputs: Mapping[Path, str]) -> set[Path]:
    return {path.resolve() for path in outputs}


def actual_generated_files() -> set[Path]:
    files: set[Path] = set()
    for root, suffixes in (
        (BACKEND_GENERATED, (".py",)),
        (FRONTEND_GENERATED, (".ts", ".json")),
    ):
        if root.is_dir():
            for suffix in suffixes:
                files.update(path.resolve() for path in root.glob(f"*{suffix}"))
    return files


def write_outputs(outputs: Mapping[Path, str]) -> None:
    expected = expected_generated_files(outputs)
    for stale in sorted(actual_generated_files() - expected):
        stale.unlink()
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"Generated {len(outputs)} contract files.")


def check_outputs(outputs: Mapping[Path, str]) -> int:
    failures: list[str] = []
    expected = expected_generated_files(outputs)
    for path, content in outputs.items():
        if not path.is_file():
            failures.append(f"missing generated file: {path.relative_to(PROJECT_ROOT)}")
        elif path.read_text(encoding="utf-8") != content:
            failures.append(
                f"outdated generated file: {path.relative_to(PROJECT_ROOT)}"
            )
    for stale in sorted(actual_generated_files() - expected):
        failures.append(f"stale generated file: {stale.relative_to(PROJECT_ROOT)}")
    if failures:
        print("Generated contract diff check FAILED:", file=sys.stderr)
        for failure in failures:
            print(f"- {failure}", file=sys.stderr)
        print("Run `make generate-contracts` and commit the result.", file=sys.stderr)
        return 1
    print(f"Generated contract diff check PASSED: {len(outputs)} files are current.")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare committed generated files without modifying them.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        outputs = render_outputs()
    except (GenerationError, OSError, ValueError, yaml.YAMLError) as exc:
        print(f"Contract generation failed: {exc}", file=sys.stderr)
        return 2
    if args.check:
        return check_outputs(outputs)
    write_outputs(outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
